import {
  AuditLog,
  BroadcastNotification,
  Caisse,
  CaisseMovement,
  Client,
  ClientPayment,
  Delivery,
  Employee,
  Establishment,
  Expense,
  InventoryItem,
  JobPosition,
  Order,
  PermissionSet,
  SaaSEditorPermissions,
  SaaSEditorUser,
  SaaSGlobalSettings,
  SaaSInvoice,
  SaaSPlan,
  SaaSSubscriptionPayment,
  ServiceItem,
  Tenant,
} from '../types';

export const DEFAULT_PERMISSIONS_ALL: PermissionSet = {
  canCreateClient: true,
  canEditClient: true,
  canDeleteClient: true,
  canViewClients: true,
  canCreateOrder: true,
  canEditOrder: true,
  canDeleteOrder: true,
  canViewOrders: true,
  canChangeOrderStatus: true,
  canApplyDiscount: true,
  canDeliverOrder: true,
  canManagePrices: true,
  canManageServices: true,
  canAcceptPayment: true,
  canRefundPayment: true,
  canCloseCaisse: true,
  canViewCashRegister: true,
  canViewRevenue: true,
  canViewProfits: true,
  canManageExpenses: true,
  canManageEmployees: true,
  canManageJobs: true,
  canViewSalaries: true,
  canManageStock: true,
  canManageDeliveries: true,
  canManageAgencies: true,
  canManageSettings: true,
  canViewAuditLogs: true,
};

export const DEFAULT_PERMISSIONS_RECEPTIONIST: PermissionSet = {
  canCreateClient: true,
  canEditClient: true,
  canDeleteClient: false,
  canViewClients: true,
  canCreateOrder: true,
  canEditOrder: true,
  canDeleteOrder: false,
  canViewOrders: true,
  canChangeOrderStatus: true,
  canApplyDiscount: false,
  canDeliverOrder: true,
  canManagePrices: false,
  canManageServices: false,
  canAcceptPayment: true,
  canRefundPayment: false,
  canCloseCaisse: false,
  canViewCashRegister: true,
  canViewRevenue: false,
  canViewProfits: false,
  canManageExpenses: false,
  canManageEmployees: false,
  canManageJobs: false,
  canViewSalaries: false,
  canManageStock: false,
  canManageDeliveries: true,
  canManageAgencies: false,
  canManageSettings: false,
  canViewAuditLogs: false,
};

export const DEFAULT_PERMISSIONS_CASHIER: PermissionSet = {
  canCreateClient: true,
  canEditClient: true,
  canDeleteClient: false,
  canViewClients: true,
  canCreateOrder: true,
  canEditOrder: false,
  canDeleteOrder: false,
  canViewOrders: true,
  canChangeOrderStatus: false,
  canApplyDiscount: true,
  canDeliverOrder: true,
  canManagePrices: false,
  canManageServices: false,
  canAcceptPayment: true,
  canRefundPayment: true,
  canCloseCaisse: true,
  canViewCashRegister: true,
  canViewRevenue: true,
  canViewProfits: false,
  canManageExpenses: true,
  canManageEmployees: false,
  canManageJobs: false,
  canViewSalaries: false,
  canManageStock: false,
  canManageDeliveries: false,
  canManageAgencies: false,
  canManageSettings: false,
  canViewAuditLogs: false,
};

export const DEFAULT_PERMISSIONS_WASHER: PermissionSet = {
  canCreateClient: false,
  canEditClient: false,
  canDeleteClient: false,
  canViewClients: false,
  canCreateOrder: false,
  canEditOrder: false,
  canDeleteOrder: false,
  canViewOrders: true,
  canChangeOrderStatus: true,
  canApplyDiscount: false,
  canDeliverOrder: false,
  canManagePrices: false,
  canManageServices: false,
  canAcceptPayment: false,
  canRefundPayment: false,
  canCloseCaisse: false,
  canViewCashRegister: false,
  canViewRevenue: false,
  canViewProfits: false,
  canManageExpenses: false,
  canManageEmployees: false,
  canManageJobs: false,
  canViewSalaries: false,
  canManageStock: true,
  canManageDeliveries: false,
  canManageAgencies: false,
  canManageSettings: false,
  canViewAuditLogs: false,
};

export const DEFAULT_PERMISSIONS_IRONER: PermissionSet = {
  canCreateClient: false,
  canEditClient: false,
  canDeleteClient: false,
  canViewClients: false,
  canCreateOrder: false,
  canEditOrder: false,
  canDeleteOrder: false,
  canViewOrders: true,
  canChangeOrderStatus: true,
  canApplyDiscount: false,
  canDeliverOrder: false,
  canManagePrices: false,
  canManageServices: false,
  canAcceptPayment: false,
  canRefundPayment: false,
  canCloseCaisse: false,
  canViewCashRegister: false,
  canViewRevenue: false,
  canViewProfits: false,
  canManageExpenses: false,
  canManageEmployees: false,
  canManageJobs: false,
  canViewSalaries: false,
  canManageStock: false,
  canManageDeliveries: false,
  canManageAgencies: false,
  canManageSettings: false,
  canViewAuditLogs: false,
};

export const DEFAULT_PERMISSIONS_DRIVER: PermissionSet = {
  canCreateClient: false,
  canEditClient: false,
  canDeleteClient: false,
  canViewClients: true,
  canCreateOrder: false,
  canEditOrder: false,
  canDeleteOrder: false,
  canViewOrders: true,
  canChangeOrderStatus: true,
  canApplyDiscount: false,
  canDeliverOrder: true,
  canManagePrices: false,
  canManageServices: false,
  canAcceptPayment: true,
  canRefundPayment: false,
  canCloseCaisse: false,
  canViewCashRegister: false,
  canViewRevenue: false,
  canViewProfits: false,
  canManageExpenses: false,
  canManageEmployees: false,
  canManageJobs: false,
  canViewSalaries: false,
  canManageStock: false,
  canManageDeliveries: true,
  canManageAgencies: false,
  canManageSettings: false,
  canViewAuditLogs: false,
};

export const DEFAULT_PERMISSIONS_MANAGER: PermissionSet = {
  canCreateClient: true,
  canEditClient: true,
  canDeleteClient: true,
  canViewClients: true,
  canCreateOrder: true,
  canEditOrder: true,
  canDeleteOrder: true,
  canViewOrders: true,
  canChangeOrderStatus: true,
  canApplyDiscount: true,
  canDeliverOrder: true,
  canManagePrices: false,
  canManageServices: false,
  canAcceptPayment: true,
  canRefundPayment: true,
  canCloseCaisse: true,
  canViewCashRegister: true,
  canViewRevenue: true,
  canViewProfits: true,
  canManageExpenses: true,
  canManageEmployees: true,
  canManageJobs: true,
  canViewSalaries: false,
  canManageStock: true,
  canManageDeliveries: true,
  canManageAgencies: false,
  canManageSettings: false,
  canViewAuditLogs: true,
};

export const PREDEFINED_JOBS_CATALOG: Omit<JobPosition, 'id' | 'tenantId'>[] = [
  {
    title: 'Gérant de Pressing',
    code: 'GER-01',
    department: 'Direction & Exploitation',
    description: 'Gestion globale des opérations quotidiennes, supervision du personnel, contrôle de caisse et qualité.',
    contractType: 'CDI',
    baseSalary: 250000,
    remunerationMode: 'fixed_commission',
    commissionRate: 3,
    workingHours: '07h30 - 19h00',
    workingDays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    permissions: DEFAULT_PERMISSIONS_MANAGER,
    isPredefined: true,
    status: 'active',
  },
  {
    title: 'Responsable Pressing & Exploitation',
    code: 'RESP-01',
    department: 'Exploitation',
    description: 'Coordination de la chaîne de production et suivi du respect des délais de livraison.',
    contractType: 'CDI',
    baseSalary: 200000,
    remunerationMode: 'fixed',
    workingHours: '08h00 - 18h30',
    workingDays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    permissions: DEFAULT_PERMISSIONS_MANAGER,
    isPredefined: true,
    status: 'active',
  },
  {
    title: 'Réceptionniste / Agent d’Accueil',
    code: 'RECEP-01',
    department: 'Accueil & Caisse',
    description: 'Accueil des clients, enregistrement des dépôts, identification des défauts et restitution des vêtements.',
    contractType: 'CDI',
    baseSalary: 120000,
    remunerationMode: 'fixed_commission',
    commissionRate: 1.5,
    workingHours: '07h30 - 19h30',
    workingDays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    permissions: DEFAULT_PERMISSIONS_RECEPTIONIST,
    isPredefined: true,
    status: 'active',
  },
  {
    title: 'Caissier Principal',
    code: 'CAIS-01',
    department: 'Accueil & Caisse',
    description: 'Encaissement des règlements Wave, Orange Money, MTN, Moov et espèces, tenue et clôture journalière.',
    contractType: 'CDI',
    baseSalary: 130000,
    remunerationMode: 'fixed',
    workingHours: '07h30 - 19h30',
    workingDays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    permissions: DEFAULT_PERMISSIONS_CASHIER,
    isPredefined: true,
    status: 'active',
  },
  {
    title: 'Agent de Tri & Marquage',
    code: 'TRI-01',
    department: 'Atelier & Blanchisserie',
    description: 'Tri des textiles selon la matière, la couleur, étiquetage des pièces avec code-barres.',
    contractType: 'CDD',
    baseSalary: 90000,
    remunerationMode: 'fixed',
    workingHours: '08h00 - 17h30',
    workingDays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    permissions: DEFAULT_PERMISSIONS_WASHER,
    isPredefined: true,
    status: 'active',
  },
  {
    title: 'Laveur & Nettoyeur Textile',
    code: 'LAV-01',
    department: 'Atelier & Blanchisserie',
    description: 'Prise en charge du lavage eau/aquanettoyage, dosage des détergents et adoucissants.',
    contractType: 'CDI',
    baseSalary: 110000,
    remunerationMode: 'fixed',
    workingHours: '07h30 - 17h30',
    workingDays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    permissions: DEFAULT_PERMISSIONS_WASHER,
    isPredefined: true,
    status: 'active',
  },
  {
    title: 'Agent de Nettoyage à Sec',
    code: 'DRY-01',
    department: 'Atelier & Blanchisserie',
    description: 'Conduite des machines de nettoyage à sec solvant/silicone pour costumes et robes délicates.',
    contractType: 'CDI',
    baseSalary: 130000,
    remunerationMode: 'fixed',
    workingHours: '08h00 - 17h30',
    workingDays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    permissions: DEFAULT_PERMISSIONS_WASHER,
    isPredefined: true,
    status: 'active',
  },
  {
    title: 'Agent de Détachage Expert',
    code: 'DET-01',
    department: 'Atelier & Blanchisserie',
    description: 'Traitement expert des taches complexes (graisse, encre, sang, vin, rouille, cambouis) sur table de détachage.',
    contractType: 'CDI',
    baseSalary: 125000,
    remunerationMode: 'fixed',
    workingHours: '08h00 - 17h30',
    workingDays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    permissions: DEFAULT_PERMISSIONS_WASHER,
    isPredefined: true,
    status: 'active',
  },
  {
    title: 'Repasseur / Maître Repasseur',
    code: 'REP-01',
    department: 'Finition & Repassage',
    description: 'Repassage professionnel des chemises, costumes, robes, boubous Bazin et Pagnes Kita.',
    contractType: 'CDI',
    baseSalary: 120000,
    remunerationMode: 'fixed_commission',
    commissionRate: 2,
    workingHours: '08h00 - 18h00',
    workingDays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    permissions: DEFAULT_PERMISSIONS_IRONER,
    isPredefined: true,
    status: 'active',
  },
  {
    title: 'Agent de Pliage & Conditionnement',
    code: 'COND-01',
    department: 'Finition & Repassage',
    description: 'Pliage soigné, houssage sous film polyéthylène, mise sur cintre et accrochage au convoyeur.',
    contractType: 'CDD',
    baseSalary: 95000,
    remunerationMode: 'fixed',
    workingHours: '08h30 - 18h00',
    workingDays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    permissions: DEFAULT_PERMISSIONS_IRONER,
    isPredefined: true,
    status: 'active',
  },
  {
    title: 'Contrôleur Qualité',
    code: 'CQ-01',
    department: 'Contrôle & Qualité',
    description: 'Inspection finale des pièces (propreté, absence de plis parasites, boutons en place, odeur fraîche).',
    contractType: 'CDI',
    baseSalary: 135000,
    remunerationMode: 'fixed',
    workingHours: '08h00 - 18h00',
    workingDays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    permissions: DEFAULT_PERMISSIONS_MANAGER,
    isPredefined: true,
    status: 'active',
  },
  {
    title: 'Chauffeur-Livreur à Domicile',
    code: 'LIV-01',
    department: 'Logistique & Livraison',
    description: 'Collecte et livraison des vêtements chez les particuliers et entreprises avec smartphone et encaissement.',
    contractType: 'CDI',
    baseSalary: 110000,
    remunerationMode: 'fixed_commission',
    commissionRate: 5,
    workingHours: '08h00 - 19h00',
    workingDays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    permissions: DEFAULT_PERMISSIONS_DRIVER,
    isPredefined: true,
    status: 'active',
  },
  {
    title: 'Responsable Logistique & Flotte',
    code: 'LOG-01',
    department: 'Logistique & Livraison',
    description: 'Organisation des tournées de ramassage et distribution entre ateliers centraux et dépôts relais.',
    contractType: 'CDI',
    baseSalary: 180000,
    remunerationMode: 'fixed',
    workingHours: '07h30 - 18h30',
    workingDays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    permissions: DEFAULT_PERMISSIONS_MANAGER,
    isPredefined: true,
    status: 'active',
  },
  {
    title: 'Comptable d’Exploitation',
    code: 'COMPT-01',
    department: 'Administration & Finance',
    description: 'Rapprochement bancaire, suivi des dépenses, factures SaaS et clôtures mensuelles.',
    contractType: 'CDI',
    baseSalary: 220000,
    remunerationMode: 'fixed',
    workingHours: '08h00 - 17h00',
    workingDays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven'],
    permissions: DEFAULT_PERMISSIONS_MANAGER,
    isPredefined: true,
    status: 'active',
  },
  {
    title: 'Technicien de Maintenance Machines',
    code: 'TECH-01',
    department: 'Technique & Maintenance',
    description: 'Entretien préventif et curatif des lave-linges industriels, séchoirs rotatifs et générateurs vapeur.',
    contractType: 'CDI',
    baseSalary: 175000,
    remunerationMode: 'fixed',
    workingHours: '08h00 - 17h30',
    workingDays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    permissions: DEFAULT_PERMISSIONS_MANAGER,
    isPredefined: true,
    status: 'active',
  },
];

export const INITIAL_SAAS_PLANS: SaaSPlan[] = [
  {
    id: 'plan-basic',
    tier: 'basic',
    name: 'Formule STARTER',
    priceMonthly: 25000,
    priceYearly: 250000,
    maxEstablishments: 1,
    maxUsers: 3,
    maxOrdersPerMonth: 300,
    features: [
      '1 Établissement / Agence',
      'Jusqu’à 3 employés',
      'Caisse & Dépôts rapides',
      'Gestion des clients & QR Tickets',
      'Paiements Mobile Money & Espèces',
      'Rapports d’activité journaliers',
      'Support par WhatsApp',
    ],
    isPopular: false,
  },
  {
    id: 'plan-pro',
    tier: 'pro',
    name: 'Formule PRO EXPANSION',
    priceMonthly: 50000,
    priceYearly: 500000,
    maxEstablishments: 3,
    maxUsers: 10,
    maxOrdersPerMonth: 1500,
    features: [
      'Jusqu’à 3 Agences / Établissements',
      'Jusqu’à 10 employés',
      'Postes & Emplois personnalisés illimités',
      'Matrice de permissions RBAC avancée',
      'Module Livraison & Tournées livreurs',
      'Gestion des stocks & consommables',
      'Gestion des dépenses et marge brute',
      'Notifications SMS / WhatsApp automatisées',
      'Rapports statistiques avancés',
    ],
    isPopular: true,
  },
  {
    id: 'plan-premium',
    tier: 'premium',
    name: 'Formule ENTERPRISE PREMIUM',
    priceMonthly: 95000,
    priceYearly: 950000,
    maxEstablishments: -1, // Unlimited
    maxUsers: -1,
    maxOrdersPerMonth: -1,
    features: [
      'Établissements & Agences illimités',
      'Utilisateurs & Employés illimités',
      'Multi-ateliers industriels & Dépôts relais',
      'Comptabilité analytique & Exports Excel/PDF',
      'API Webhooks de paiement directe',
      'Portail de suivi client en temps réel',
      'Sauvegardes automatiques quotidiennes',
      'Accompagnement & Chef de projet dédié',
    ],
    isPopular: false,
  },
];

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'tenant-elegance',
    companyName: 'Pressing Élégance Abidjan',
    slug: 'pressing-elegance',
    ownerName: 'Jean-Marc Kouadio',
    ownerEmail: 'jm.kouadio@pressingelegance.ci',
    ownerPhone: '+225 07 08 12 34 56',
    ownerWhatsapp: '+225 07 08 12 34 56',
    currency: 'FCFA',
    country: "Côte d'Ivoire",
    city: 'Abidjan',
    registeredDate: '2026-01-10',
    status: 'active',
    planTier: 'pro',
    planName: 'Formule PRO EXPANSION',
    subscriptionStartDate: '2026-01-10',
    subscriptionEndDate: '2026-09-10',
    lastPaymentDate: '2026-08-10',
    outstandingBalance: 0,
    establishmentsCount: 3,
    usersCount: 8,
    receiptHeader: 'PRESSING ÉLÉGANCE ABIDJAN\nSpécialiste Bazin, Costumes & Soieries',
    receiptFooter: 'Merci pour votre confiance ! Tout vêtement non réclamé après 90 jours sera cédé.',
    taxRate: 0,
    expressSurchargeRate: 50,
    customWorkflowStages: [
      { key: 'deposited', label: 'Déposée', enabled: true },
      { key: 'sorting', label: 'Tri & Marquage', enabled: true },
      { key: 'washing', label: 'En lavage', enabled: true },
      { key: 'drying', label: 'En séchage', enabled: true },
      { key: 'ironing', label: 'En repassage', enabled: true },
      { key: 'quality_check', label: 'Contrôle Qualité', enabled: true },
      { key: 'ready', label: 'Prête en boutique', enabled: true },
      { key: 'in_delivery', label: 'En cours de livraison', enabled: true },
      { key: 'delivered', label: 'Livrée / Restituée', enabled: true },
    ],
  },
  {
    id: 'tenant-clean-net',
    companyName: 'Clean & Net Pressing Riviera',
    slug: 'clean-net-riviera',
    ownerName: 'Awa Traoré',
    ownerEmail: 'awa.traore@cleannet.ci',
    ownerPhone: '+225 05 44 88 99 00',
    ownerWhatsapp: '+225 05 44 88 99 00',
    currency: 'FCFA',
    country: "Côte d'Ivoire",
    city: 'Abidjan',
    registeredDate: '2026-08-01',
    status: 'trial',
    planTier: 'basic',
    planName: 'Période d’essai Starter',
    trialStartDate: '2026-08-01',
    trialEndDate: '2026-08-20',
    outstandingBalance: 0,
    establishmentsCount: 1,
    usersCount: 2,
    receiptHeader: 'CLEAN & NET PRESSING - PALMERAIE\nNettoyage Express & Qualité Premium',
    receiptFooter: 'Service garanti 48h. Conservez votre ticket pour le retrait.',
    taxRate: 0,
    expressSurchargeRate: 40,
    customWorkflowStages: [
      { key: 'deposited', label: 'Déposée', enabled: true },
      { key: 'washing', label: 'Lavage & Détachage', enabled: true },
      { key: 'ironing', label: 'Repassage', enabled: true },
      { key: 'ready', label: 'Prête', enabled: true },
      { key: 'delivered', label: 'Retirée', enabled: true },
    ],
  },
  {
    id: 'tenant-royal-prestige',
    companyName: 'Royal Prestige Pressing CI',
    slug: 'royal-prestige',
    ownerName: 'Stéphane Bamba',
    ownerEmail: 'sbamba@royalprestige.ci',
    ownerPhone: '+225 01 02 03 04 05',
    ownerWhatsapp: '+225 01 02 03 04 05',
    currency: 'FCFA',
    country: "Côte d'Ivoire",
    city: 'Abidjan / Yamoussoukro',
    registeredDate: '2025-11-15',
    status: 'active',
    planTier: 'premium',
    planName: 'Formule ENTERPRISE PREMIUM',
    subscriptionStartDate: '2025-11-15',
    subscriptionEndDate: '2026-11-15',
    lastPaymentDate: '2025-11-15',
    outstandingBalance: 0,
    establishmentsCount: 4,
    usersCount: 16,
    receiptHeader: 'ROYAL PRESTIGE PRESSING & BLANCHISSERIE INDUSTRIELLE',
    receiptFooter: 'Service VIP, Literie & Uniformes professionnels.',
    taxRate: 18,
    expressSurchargeRate: 50,
    customWorkflowStages: [
      { key: 'deposited', label: 'Déposée', enabled: true },
      { key: 'sorting', label: 'Tri & Marquage', enabled: true },
      { key: 'washing', label: 'En lavage', enabled: true },
      { key: 'drying', label: 'En séchage', enabled: true },
      { key: 'ironing', label: 'En repassage', enabled: true },
      { key: 'quality_check', label: 'Contrôle Qualité', enabled: true },
      { key: 'ready', label: 'Prête en boutique', enabled: true },
      { key: 'in_delivery', label: 'En livraison', enabled: true },
      { key: 'delivered', label: 'Livrée / Restituée', enabled: true },
    ],
  },
  {
    id: 'tenant-ivoire-express',
    companyName: 'Ivoire Express Blanchisserie',
    slug: 'ivoire-express',
    ownerName: 'Clarisse Yao',
    ownerEmail: 'clarisse.yao@ivoirepress.ci',
    ownerPhone: '+225 07 77 88 99 11',
    ownerWhatsapp: '+225 07 77 88 99 11',
    currency: 'FCFA',
    country: "Côte d'Ivoire",
    city: 'Abidjan',
    registeredDate: '2026-05-10',
    status: 'suspended',
    planTier: 'basic',
    planName: 'Formule STARTER',
    subscriptionStartDate: '2026-05-10',
    subscriptionEndDate: '2026-07-10',
    lastPaymentDate: '2026-05-10',
    outstandingBalance: 25000,
    establishmentsCount: 1,
    usersCount: 2,
    receiptHeader: 'IVOIRE EXPRESS BLANCHISSERIE',
    receiptFooter: 'Merci de votre visite.',
    taxRate: 0,
    expressSurchargeRate: 30,
    customWorkflowStages: [
      { key: 'deposited', label: 'Déposée', enabled: true },
      { key: 'washing', label: 'Lavage', enabled: true },
      { key: 'ironing', label: 'Repassage', enabled: true },
      { key: 'ready', label: 'Prête', enabled: true },
      { key: 'delivered', label: 'Livrée', enabled: true },
    ],
  },
];

export const INITIAL_ESTABLISHMENTS: Establishment[] = [
  {
    id: 'est-angre',
    tenantId: 'tenant-elegance',
    name: 'Agence Cocody Angré 8e Tranche',
    code: 'ANG-01',
    city: 'Abidjan',
    neighborhood: 'Cocody Angré 8e Tranche, Carrefour Nelson Mandela',
    address: 'Immeuble Le Balisier, RDC',
    phone: '+225 27 22 45 10 20',
    whatsapp: '+225 07 08 12 34 56',
    managerName: 'Bakary Soro',
    isMain: true,
    status: 'active',
  },
  {
    id: 'est-marcory',
    tenantId: 'tenant-elegance',
    name: 'Agence Marcory Zone 4',
    code: 'MAR-02',
    city: 'Abidjan',
    neighborhood: 'Marcory Zone 4C, Rue du Dr Blanchard',
    address: 'En face de la clinique Farhat',
    phone: '+225 27 21 35 78 90',
    whatsapp: '+225 07 08 12 34 57',
    managerName: 'Marcelle N’Guessan',
    isMain: false,
    status: 'active',
  },
  {
    id: 'est-yopougon',
    tenantId: 'tenant-elegance',
    name: 'Agence Yopougon Maroc',
    code: 'YOP-03',
    city: 'Abidjan',
    neighborhood: 'Yopougon Maroc, Carrefour Antenne',
    address: 'Près de la Pharmacie du Maroc',
    phone: '+225 27 23 49 11 22',
    whatsapp: '+225 07 08 12 34 58',
    managerName: 'Koffi Arsène',
    isMain: false,
    status: 'active',
  },
  {
    id: 'est-palmeraie',
    tenantId: 'tenant-clean-net',
    name: 'Agence Riviera Palmeraie',
    code: 'PAL-01',
    city: 'Abidjan',
    neighborhood: 'Riviera Palmeraie, Rond-point Guiraud',
    address: 'Villa 142, Rue Ministre',
    phone: '+225 27 22 49 80 00',
    whatsapp: '+225 05 44 88 99 00',
    managerName: 'Awa Traoré',
    isMain: true,
    status: 'active',
  },
];

export const INITIAL_SERVICES: ServiceItem[] = [
  // Vêtements quotidiens
  {
    id: 'srv-chemise',
    tenantId: 'tenant-elegance',
    name: 'Chemise classique (Homme / Femme)',
    category: 'Vêtements quotidiens',
    description: 'Lavage, amidonnage léger et repassage sur cintre ou pliée',
    priceStandard: 1000,
    priceExpress: 1500,
    estimatedProcessingHours: 24,
    status: 'active',
  },
  {
    id: 'srv-pantalon',
    tenantId: 'tenant-elegance',
    name: 'Pantalon / Jeans / Chino',
    category: 'Vêtements quotidiens',
    description: 'Nettoyage approfondi avec pli net et repassage impeccable',
    priceStandard: 1200,
    priceExpress: 1800,
    estimatedProcessingHours: 24,
    status: 'active',
  },
  {
    id: 'srv-tshirt-polo',
    tenantId: 'tenant-elegance',
    name: 'T-Shirt / Polo',
    category: 'Vêtements quotidiens',
    description: 'Lavage doux, détachage col et repassage vapeur',
    priceStandard: 800,
    priceExpress: 1200,
    estimatedProcessingHours: 24,
    status: 'active',
  },
  {
    id: 'srv-robe-simple',
    tenantId: 'tenant-elegance',
    name: 'Robe de ville / Jupe simple',
    category: 'Vêtements quotidiens',
    description: 'Soin délicat des tissus synthétiques et cotons',
    priceStandard: 1500,
    priceExpress: 2300,
    estimatedProcessingHours: 24,
    status: 'active',
  },

  // Traditionnel & Africain
  {
    id: 'srv-bazin-riche-3p',
    tenantId: 'tenant-elegance',
    name: 'Boubou Bazin Riche (Complet 3 pièces)',
    category: 'Traditionnel / Bazin & Kita',
    description: 'Frappage traditionnel, brillance éclatante et parfumage aux senteurs locales',
    priceStandard: 5000,
    priceExpress: 7500,
    estimatedProcessingHours: 48,
    status: 'active',
  },
  {
    id: 'srv-bazin-simple',
    tenantId: 'tenant-elegance',
    name: 'Bazin 2 pièces ou Gandoura',
    category: 'Traditionnel / Bazin & Kita',
    description: 'Lavage à sec ou aquanettoyage délicat avec finition éclat',
    priceStandard: 3500,
    priceExpress: 5000,
    estimatedProcessingHours: 48,
    status: 'active',
  },
  {
    id: 'srv-pagne-kita',
    tenantId: 'tenant-elegance',
    name: 'Tenue en Pagne Kita / Pagne Baoulé tissé',
    category: 'Traditionnel / Bazin & Kita',
    description: 'Nettoyage hydrofuge spécial pour préserver les fils dorés et tissages lourds',
    priceStandard: 6000,
    priceExpress: 9000,
    estimatedProcessingHours: 48,
    status: 'active',
  },
  {
    id: 'srv-robe-dentelle',
    tenantId: 'tenant-elegance',
    name: 'Robe en Dentelle / Soie sauvage avec perles',
    category: 'Traditionnel / Bazin & Kita',
    description: 'Soin haute couture, protection des perles et broderies',
    priceStandard: 4500,
    priceExpress: 6500,
    estimatedProcessingHours: 48,
    status: 'active',
  },

  // Costumes & Luxe
  {
    id: 'srv-costume-2p',
    tenantId: 'tenant-elegance',
    name: 'Costume 2 pièces (Veste + Pantalon)',
    category: 'Costumes & Luxe',
    description: 'Nettoyage à sec professionnel, mise sous forme de la veste et anti-lustrage',
    priceStandard: 3500,
    priceExpress: 5000,
    estimatedProcessingHours: 24,
    status: 'active',
  },
  {
    id: 'srv-costume-3p',
    tenantId: 'tenant-elegance',
    name: 'Costume 3 pièces (Veste + Gilet + Pantalon)',
    category: 'Costumes & Luxe',
    description: 'Nettoyage complet pressing de luxe avec cintre renforcé',
    priceStandard: 4500,
    priceExpress: 6500,
    estimatedProcessingHours: 24,
    status: 'active',
  },
  {
    id: 'srv-robe-soiree',
    tenantId: 'tenant-elegance',
    name: 'Robe de soirée / Robe de mariée',
    category: 'Costumes & Luxe',
    description: 'Traitement personnalisé des traînes, perles et doublures délicates',
    priceStandard: 10000,
    priceExpress: 15000,
    estimatedProcessingHours: 72,
    status: 'active',
  },
  {
    id: 'srv-veste-seule',
    tenantId: 'tenant-elegance',
    name: 'Veste de blazer / Manteau léger',
    category: 'Costumes & Luxe',
    description: 'Pressing soigné avec désodorisation',
    priceStandard: 2500,
    priceExpress: 3800,
    estimatedProcessingHours: 24,
    status: 'active',
  },

  // Maison & Blanchisserie
  {
    id: 'srv-couette-2p',
    tenantId: 'tenant-elegance',
    name: 'Couette 2 places / Édredon en duvet',
    category: 'Maison & Blanchisserie',
    description: 'Lavage machine grand volume antibactérien, séchage gonflant et emballage sous vide',
    priceStandard: 5000,
    priceExpress: 7500,
    estimatedProcessingHours: 48,
    status: 'active',
  },
  {
    id: 'srv-draps-complet',
    tenantId: 'tenant-elegance',
    name: 'Parure de lit (Drap housse + Drap plat + 2 Taies)',
    category: 'Maison & Blanchisserie',
    description: 'Blanchissage éclat et repassage calandre industrielle',
    priceStandard: 3000,
    priceExpress: 4500,
    estimatedProcessingHours: 24,
    status: 'active',
  },
  {
    id: 'srv-rideaux',
    tenantId: 'tenant-elegance',
    name: 'Rideaux & Voilages (le mètre carré)',
    category: 'Maison & Blanchisserie',
    description: 'Dépoussiérage et lavage avec traitement anti-acarien',
    priceStandard: 1500,
    priceExpress: 2200,
    estimatedProcessingHours: 48,
    status: 'active',
  },

  // Chaussures & Maroquinerie
  {
    id: 'srv-sneakers',
    tenantId: 'tenant-elegance',
    name: 'Nettoyage Baskets & Sneakers Deluxe',
    category: 'Chaussures & Maroquinerie',
    description: 'Nettoyage semelle, empeigne, lacets et traitement imperméabilisant',
    priceStandard: 3000,
    priceExpress: 4500,
    estimatedProcessingHours: 48,
    status: 'active',
  },
  {
    id: 'srv-chaussures-cuir',
    tenantId: 'tenant-elegance',
    name: 'Chaussures en cuir / Escarpins (Cirage & Soin)',
    category: 'Chaussures & Maroquinerie',
    description: 'Nettoyage crème nourrissante, lustrage et protection',
    priceStandard: 2500,
    priceExpress: 3500,
    estimatedProcessingHours: 24,
    status: 'active',
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-001',
    tenantId: 'tenant-elegance',
    clientCode: 'CLI-001',
    firstName: 'Amadou',
    lastName: 'Koné',
    phone: '+225 07 11 22 33 44',
    whatsapp: '+225 07 11 22 33 44',
    email: 'amadou.kone@gmail.com',
    address: 'Cocody Danga, Villa 24',
    neighborhood: 'Cocody Danga',
    city: 'Abidjan',
    createdAt: '2026-01-15',
    totalOrders: 14,
    totalSpent: 125000,
    outstandingBalance: 0,
    loyaltyPoints: 125,
    notes: 'Client VIP - Préfère amidonnage moyen pour ses chemises',
    preferredContact: 'whatsapp',
  },
  {
    id: 'cli-002',
    tenantId: 'tenant-elegance',
    clientCode: 'CLI-002',
    firstName: 'Fatou',
    lastName: 'Bamba Epouse Diop',
    phone: '+225 05 22 33 44 55',
    whatsapp: '+225 05 22 33 44 55',
    email: 'fatou.diop@yahoo.fr',
    address: 'Angré 8e Tranche, Cité Star 5',
    neighborhood: 'Angré 8e Tranche',
    city: 'Abidjan',
    createdAt: '2026-02-01',
    totalOrders: 9,
    totalSpent: 84000,
    outstandingBalance: 3500,
    loyaltyPoints: 84,
    notes: 'Dépose régulièrement des Bazin Riche 3 pièces',
    preferredContact: 'whatsapp',
  },
  {
    id: 'cli-003',
    tenantId: 'tenant-elegance',
    clientCode: 'CLI-003',
    firstName: 'Yves',
    lastName: 'N’Dri',
    phone: '+225 01 99 88 77 66',
    whatsapp: '+225 01 99 88 77 66',
    email: 'yves.ndri@cabinet-ndri.ci',
    address: 'Marcory Zone 4, Résidence Marina',
    neighborhood: 'Marcory Zone 4',
    city: 'Abidjan',
    createdAt: '2026-02-12',
    totalOrders: 6,
    totalSpent: 52000,
    outstandingBalance: 0,
    loyaltyPoints: 52,
    notes: 'Demande toujours la livraison au bureau à Marcory',
    preferredContact: 'sms',
  },
  {
    id: 'cli-004',
    tenantId: 'tenant-elegance',
    clientCode: 'CLI-004',
    firstName: 'Chantal',
    lastName: 'Kouassi',
    phone: '+225 07 45 67 89 01',
    whatsapp: '+225 07 45 67 89 01',
    email: 'chantalkouassi@outlook.com',
    address: 'Yopougon Niangon Sud',
    neighborhood: 'Yopougon Niangon',
    city: 'Abidjan',
    createdAt: '2026-03-05',
    totalOrders: 4,
    totalSpent: 28000,
    outstandingBalance: 0,
    loyaltyPoints: 28,
    notes: 'Robes en dentelle délicates',
    preferredContact: 'whatsapp',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-0842',
    tenantId: 'tenant-elegance',
    establishmentId: 'est-angre',
    establishmentName: 'Agence Cocody Angré 8e Tranche',
    orderNumber: 'MPP-2026-0842',
    clientId: 'cli-001',
    clientName: 'Amadou Koné',
    clientPhone: '+225 07 11 22 33 44',
    clientWhatsapp: '+225 07 11 22 33 44',
    items: [
      {
        id: 'item-1',
        serviceId: 'srv-chemise',
        serviceName: 'Chemise classique (Homme / Femme)',
        category: 'Vêtements quotidiens',
        unitPrice: 1000,
        quantity: 4,
        totalPrice: 4000,
        color: 'Blanc & Bleu ciel',
        issues: ['Col légèrement jauni'],
        treatmentNotes: 'Détachage col avant lavage',
        tagNumber: 'TAG-0842-1',
      },
      {
        id: 'item-2',
        serviceId: 'srv-costume-2p',
        serviceName: 'Costume 2 pièces (Veste + Pantalon)',
        category: 'Costumes & Luxe',
        unitPrice: 3500,
        quantity: 1,
        totalPrice: 3500,
        color: 'Bleu nuit',
        treatmentNotes: 'Nettoyage à sec spécial',
        tagNumber: 'TAG-0842-2',
      },
    ],
    itemCount: 5,
    subtotal: 7500,
    isExpress: false,
    expressFee: 0,
    deliveryFee: 0,
    discountAmount: 0,
    totalAmount: 7500,
    paidAmount: 7500,
    remainingBalance: 0,
    depositDate: '2026-08-15 09:30',
    promisedPickupDate: '2026-08-17',
    promisedPickupTime: '17:00',
    status: 'ironing',
    statusHistory: [
      {
        status: 'deposited',
        timestamp: '2026-08-15 09:30',
        updatedByEmployeeName: 'Sarah K. (Réception)',
        notes: 'Dépôt effectué et payé par Wave',
      },
      {
        status: 'sorting',
        timestamp: '2026-08-15 10:15',
        updatedByEmployeeName: 'Moussa T. (Tri)',
        notes: 'Tri et étiquetage validés',
      },
      {
        status: 'washing',
        timestamp: '2026-08-15 11:30',
        updatedByEmployeeName: 'Ibrahim D. (Lavage)',
        notes: 'Lavage aquanettoyage terminé',
      },
      {
        status: 'drying',
        timestamp: '2026-08-15 14:00',
        updatedByEmployeeName: 'Ibrahim D. (Lavage)',
        notes: 'Séchage doux achevé',
      },
      {
        status: 'ironing',
        timestamp: '2026-08-16 08:30',
        updatedByEmployeeName: 'Abdoulaye S. (Repassage)',
        notes: 'En cours de repassage des chemises',
      },
    ],
    paymentStatus: 'paid',
    deliveryRequested: false,
    rackLocation: 'P-12',
    createdByEmployeeId: 'emp-sarah',
    createdByEmployeeName: 'Sarah Konan',
  },
  {
    id: 'ord-0843',
    tenantId: 'tenant-elegance',
    establishmentId: 'est-angre',
    establishmentName: 'Agence Cocody Angré 8e Tranche',
    orderNumber: 'MPP-2026-0843',
    clientId: 'cli-002',
    clientName: 'Fatou Bamba Epouse Diop',
    clientPhone: '+225 05 22 33 44 55',
    clientWhatsapp: '+225 05 22 33 44 55',
    items: [
      {
        id: 'item-3',
        serviceId: 'srv-bazin-riche-3p',
        serviceName: 'Boubou Bazin Riche (Complet 3 pièces)',
        category: 'Traditionnel / Bazin & Kita',
        unitPrice: 5000,
        quantity: 2,
        totalPrice: 10000,
        color: 'Doré / Marron chocolat',
        treatmentNotes: 'Frappage brillant demandé pour cérémonie de mariage samedi',
        tagNumber: 'TAG-0843-1',
      },
    ],
    itemCount: 2,
    subtotal: 10000,
    isExpress: true,
    expressFee: 5000,
    deliveryFee: 1500,
    discountAmount: 0,
    totalAmount: 16500,
    paidAmount: 13000,
    remainingBalance: 3500,
    depositDate: '2026-08-15 14:00',
    promisedPickupDate: '2026-08-16',
    promisedPickupTime: '18:00',
    status: 'ready',
    statusHistory: [
      {
        status: 'deposited',
        timestamp: '2026-08-15 14:00',
        updatedByEmployeeName: 'Sarah K. (Réception)',
        notes: 'Commande Express avec livraison à domicile',
      },
      {
        status: 'washing',
        timestamp: '2026-08-15 16:00',
        updatedByEmployeeName: 'Ibrahim D.',
        notes: 'Lavage délicat',
      },
      {
        status: 'ironing',
        timestamp: '2026-08-15 20:00',
        updatedByEmployeeName: 'Abdoulaye S.',
        notes: 'Frappage Bazin impeccable',
      },
      {
        status: 'quality_check',
        timestamp: '2026-08-16 07:45',
        updatedByEmployeeName: 'Bakary Soro (Gérant)',
        notes: 'Qualité validée, brillance maximale',
      },
      {
        status: 'ready',
        timestamp: '2026-08-16 08:00',
        updatedByEmployeeName: 'Sarah Konan',
        notes: 'Houssé avec cintre velours - Prêt pour le livreur',
      },
    ],
    paymentStatus: 'partial',
    deliveryRequested: true,
    deliveryAddress: 'Angré 8e Tranche, Cité Star 5, Villa 18',
    rackLocation: 'EXP-04',
    createdByEmployeeId: 'emp-sarah',
    createdByEmployeeName: 'Sarah Konan',
  },
  {
    id: 'ord-0844',
    tenantId: 'tenant-elegance',
    establishmentId: 'est-marcory',
    establishmentName: 'Agence Marcory Zone 4',
    orderNumber: 'MPP-2026-0844',
    clientId: 'cli-003',
    clientName: 'Yves N’Dri',
    clientPhone: '+225 01 99 88 77 66',
    clientWhatsapp: '+225 01 99 88 77 66',
    items: [
      {
        id: 'item-4',
        serviceId: 'srv-costume-3p',
        serviceName: 'Costume 3 pièces (Veste + Gilet + Pantalon)',
        category: 'Costumes & Luxe',
        unitPrice: 4500,
        quantity: 2,
        totalPrice: 9000,
        color: 'Gris anthracite & Noir',
        tagNumber: 'TAG-0844-1',
      },
      {
        id: 'item-5',
        serviceId: 'srv-chemise',
        serviceName: 'Chemise classique (Homme / Femme)',
        category: 'Vêtements quotidiens',
        unitPrice: 1000,
        quantity: 5,
        totalPrice: 5000,
        color: 'Assortiment',
        tagNumber: 'TAG-0844-2',
      },
    ],
    itemCount: 7,
    subtotal: 14000,
    isExpress: false,
    expressFee: 0,
    deliveryFee: 2000,
    discountAmount: 1000,
    totalAmount: 15000,
    paidAmount: 15000,
    remainingBalance: 0,
    depositDate: '2026-08-16 08:00',
    promisedPickupDate: '2026-08-18',
    promisedPickupTime: '16:00',
    status: 'sorting',
    statusHistory: [
      {
        status: 'deposited',
        timestamp: '2026-08-16 08:00',
        updatedByEmployeeName: 'Marcelle N.',
        notes: 'Dépôt agence Marcory',
      },
      {
        status: 'sorting',
        timestamp: '2026-08-16 08:20',
        updatedByEmployeeName: 'Marcelle N.',
        notes: 'Tri et étiquetage',
      },
    ],
    paymentStatus: 'paid',
    deliveryRequested: true,
    deliveryAddress: 'Marcory Zone 4, Tour BIAO 4e étage',
    rackLocation: 'M-01',
    createdByEmployeeId: 'emp-marcelle',
    createdByEmployeeName: 'Marcelle N’Guessan',
  },
];

export const INITIAL_CAISSES: Caisse[] = [
  {
    id: 'caisse-angre-main',
    tenantId: 'tenant-elegance',
    establishmentId: 'est-angre',
    name: 'Caisse Principale Angré',
    initialBalance: 50000,
    currentCashBalance: 124500,
    totalInToday: 82000,
    totalOutToday: 7500,
    theoreticalBalance: 124500,
    isOpen: true,
    lastOpenedAt: '2026-08-16 07:30',
  },
  {
    id: 'caisse-marcory-main',
    tenantId: 'tenant-elegance',
    establishmentId: 'est-marcory',
    name: 'Caisse Accueil Marcory',
    initialBalance: 30000,
    currentCashBalance: 65000,
    totalInToday: 35000,
    totalOutToday: 0,
    theoreticalBalance: 65000,
    isOpen: true,
    lastOpenedAt: '2026-08-16 08:00',
  },
  {
    id: 'caisse-yopougon-main',
    tenantId: 'tenant-elegance',
    establishmentId: 'est-yopougon',
    name: 'Caisse Yopougon Maroc',
    initialBalance: 25000,
    currentCashBalance: 48000,
    totalInToday: 23000,
    totalOutToday: 0,
    theoreticalBalance: 48000,
    isOpen: true,
    lastOpenedAt: '2026-08-16 07:45',
  },
];

export const INITIAL_CLIENT_PAYMENTS: ClientPayment[] = [
  {
    id: 'pay-001',
    tenantId: 'tenant-elegance',
    establishmentId: 'est-angre',
    orderId: 'ord-0842',
    orderNumber: 'MPP-2026-0842',
    clientId: 'cli-001',
    clientName: 'Amadou Koné',
    amount: 7500,
    paymentMethod: 'wave',
    transactionReference: 'WAVE-CI-20260815-99812',
    receiptNumber: 'REC-2026-0842',
    recordedByEmployeeId: 'emp-sarah',
    recordedByEmployeeName: 'Sarah Konan',
    date: '2026-08-15',
    time: '09:32',
    status: 'confirmed',
    isCashVerified: true,
    notes: 'Paiement Wave instantané validé',
  },
  {
    id: 'pay-002',
    tenantId: 'tenant-elegance',
    establishmentId: 'est-angre',
    orderId: 'ord-0843',
    orderNumber: 'MPP-2026-0843',
    clientId: 'cli-002',
    clientName: 'Fatou Bamba Epouse Diop',
    amount: 13000,
    paymentMethod: 'orange_money',
    transactionReference: 'OM-CI-260815-77123',
    receiptNumber: 'REC-2026-0843-1',
    recordedByEmployeeId: 'emp-sarah',
    recordedByEmployeeName: 'Sarah Konan',
    date: '2026-08-15',
    time: '14:05',
    status: 'confirmed',
    isCashVerified: true,
    notes: 'Acompte Orange Money reçu (Reste 3 500 FCFA à la livraison)',
  },
  {
    id: 'pay-003',
    tenantId: 'tenant-elegance',
    establishmentId: 'est-marcory',
    orderId: 'ord-0844',
    orderNumber: 'MPP-2026-0844',
    clientId: 'cli-003',
    clientName: 'Yves N’Dri',
    amount: 15000,
    paymentMethod: 'cash',
    transactionReference: 'CASH-REC-0844',
    receiptNumber: 'REC-2026-0844',
    recordedByEmployeeId: 'emp-marcelle',
    recordedByEmployeeName: 'Marcelle N’Guessan',
    date: '2026-08-16',
    time: '08:05',
    status: 'confirmed',
    isCashVerified: true,
    cashValidatedBy: 'Marcelle N’Guessan (Caissière)',
    notes: 'Espèces encaissées (Billet de 10 000 + Billet de 5 000)',
  },
];

export const INITIAL_SAAS_PAYMENTS: SaaSSubscriptionPayment[] = [
  {
    id: 'saas-pay-001',
    tenantId: 'tenant-elegance',
    tenantName: 'Pressing Élégance Abidjan',
    ownerName: 'Jean-Marc Kouadio',
    ownerPhone: '+225 07 08 12 34 56',
    planTier: 'pro',
    planName: 'Formule PRO EXPANSION',
    amount: 50000,
    billingCycle: 'monthly',
    paymentMethod: 'wave',
    transactionReference: 'WAVE-SAAS-20260810-0012',
    receiptNumber: 'INV-SAAS-2026-0042',
    recordedByAdminName: 'Super Admin Mon Pressing Pro',
    paymentDate: '2026-08-10',
    coverageStartDate: '2026-08-10',
    coverageEndDate: '2026-09-10',
    status: 'confirmed',
    notes: 'Renouvellement mensuel abonnement SaaS Pro Wave CI',
  },
  {
    id: 'saas-pay-002',
    tenantId: 'tenant-royal-prestige',
    tenantName: 'Royal Prestige Pressing CI',
    ownerName: 'Stéphane Bamba',
    ownerPhone: '+225 01 02 03 04 05',
    planTier: 'premium',
    planName: 'Formule ENTERPRISE PREMIUM',
    amount: 950000,
    billingCycle: 'yearly',
    paymentMethod: 'bank_transfer',
    transactionReference: 'VIR-SGBCI-20251115-992',
    receiptNumber: 'INV-SAAS-2025-0018',
    recordedByAdminName: 'Super Admin Mon Pressing Pro',
    paymentDate: '2025-11-15',
    coverageStartDate: '2025-11-15',
    coverageEndDate: '2026-11-15',
    status: 'confirmed',
    notes: 'Abonnement annuel Entreprise Premium réglé par virement SGBCI',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-001',
    tenantId: 'tenant-elegance',
    establishmentId: 'est-angre',
    establishmentName: 'Agence Cocody Angré 8e Tranche',
    category: 'Produits de lavage / Détergents',
    title: 'Achat Bidon 25L Lessive Liquide Pro & Détachant graisse',
    amount: 38000,
    paymentMethod: 'wave',
    beneficiaryOrSupplier: 'Société Ivoirienne de Chimie Textile (SICT)',
    recordedByEmployeeId: 'emp-bakary',
    recordedByEmployeeName: 'Bakary Soro (Gérant)',
    date: '2026-08-14',
    invoiceNumber: 'FAC-SICT-2026-88',
    notes: 'Livraison reçue et stockée à l’atelier Angré',
  },
  {
    id: 'exp-002',
    tenantId: 'tenant-elegance',
    establishmentId: 'est-angre',
    establishmentName: 'Agence Cocody Angré 8e Tranche',
    category: 'Carburant / Transport',
    title: 'Carburant Moto Livraison Tournée Cocody',
    amount: 7500,
    paymentMethod: 'cash',
    beneficiaryOrSupplier: 'Station TotalEnergies Angré',
    recordedByEmployeeId: 'emp-bakary',
    recordedByEmployeeName: 'Bakary Soro',
    date: '2026-08-16',
    invoiceNumber: 'TICKET-TOTAL-9912',
    notes: 'Plein de carburant moto Yamaha du livreur',
  },
  {
    id: 'exp-003',
    tenantId: 'tenant-elegance',
    establishmentId: 'est-marcory',
    establishmentName: 'Agence Marcory Zone 4',
    category: 'Emballages & Cintres',
    title: 'Carton 500 cintres métalliques + 2 rouleaux gaines housses',
    amount: 28000,
    paymentMethod: 'orange_money',
    beneficiaryOrSupplier: 'Emballages Plus Adjamé',
    recordedByEmployeeId: 'emp-marcelle',
    recordedByEmployeeName: 'Marcelle N’Guessan',
    date: '2026-08-13',
    invoiceNumber: 'EMP-2026-041',
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-001',
    tenantId: 'tenant-elegance',
    establishmentId: 'est-angre',
    name: 'Lessive Liquide Industrielle Concentrée',
    category: 'Lessives & Poudres',
    currentStock: 45,
    unit: 'litres',
    minThreshold: 20,
    costPerUnit: 1200,
    lastRestockedDate: '2026-08-14',
    supplierName: 'SICT Abidjan',
    status: 'optimal',
  },
  {
    id: 'inv-002',
    tenantId: 'tenant-elegance',
    establishmentId: 'est-angre',
    name: 'Détachant Enzymatique Taches Tenaces',
    category: 'Détachants & Solvants',
    currentStock: 6,
    unit: 'litres',
    minThreshold: 10,
    costPerUnit: 4500,
    lastRestockedDate: '2026-08-01',
    supplierName: 'SICT Abidjan',
    status: 'low',
  },
  {
    id: 'inv-003',
    tenantId: 'tenant-elegance',
    establishmentId: 'est-angre',
    name: 'Cintres métalliques renforcés',
    category: 'Cintres métalliques & plastiques',
    currentStock: 350,
    unit: 'unités',
    minThreshold: 150,
    costPerUnit: 60,
    lastRestockedDate: '2026-08-10',
    supplierName: 'Emballages Plus',
    status: 'optimal',
  },
  {
    id: 'inv-004',
    tenantId: 'tenant-elegance',
    establishmentId: 'est-angre',
    name: 'Gaine plastique housseuse transparente',
    category: 'Emballages & Housses',
    currentStock: 2,
    unit: 'rouleaux',
    minThreshold: 3,
    costPerUnit: 14000,
    lastRestockedDate: '2026-07-28',
    supplierName: 'Emballages Plus',
    status: 'low',
  },
  {
    id: 'inv-005',
    tenantId: 'tenant-elegance',
    establishmentId: 'est-angre',
    name: 'Assouplissant Parfumé Lavande Royale',
    category: 'Assouplissants',
    currentStock: 30,
    unit: 'litres',
    minThreshold: 15,
    costPerUnit: 900,
    lastRestockedDate: '2026-08-14',
    supplierName: 'SICT Abidjan',
    status: 'optimal',
  },
];

export const INITIAL_DELIVERIES: Delivery[] = [
  {
    id: 'del-001',
    tenantId: 'tenant-elegance',
    establishmentId: 'est-angre',
    orderId: 'ord-0843',
    orderNumber: 'MPP-2026-0843',
    clientId: 'cli-002',
    clientName: 'Fatou Bamba Epouse Diop',
    clientPhone: '+225 05 22 33 44 55',
    deliveryAddress: 'Angré 8e Tranche, Cité Star 5, Villa 18',
    neighborhood: 'Cocody Angré',
    deliveryFee: 1500,
    amountToCollect: 3500,
    driverId: 'emp-kouame',
    driverName: 'Kouamé Eric (Livreur Express)',
    status: 'assigned',
    requestedDate: '2026-08-16',
    requestedTimeSlot: '17h00 - 18h30',
    notes: 'Appeler 15 minutes avant arrivée. Solde 3 500 FCFA à encaisser en Wave ou Espèces.',
  },
  {
    id: 'del-002',
    tenantId: 'tenant-elegance',
    establishmentId: 'est-marcory',
    orderId: 'ord-0844',
    orderNumber: 'MPP-2026-0844',
    clientId: 'cli-003',
    clientName: 'Yves N’Dri',
    clientPhone: '+225 01 99 88 77 66',
    deliveryAddress: 'Marcory Zone 4, Tour BIAO 4e étage',
    neighborhood: 'Marcory Zone 4',
    deliveryFee: 2000,
    amountToCollect: 0,
    status: 'to_deliver',
    requestedDate: '2026-08-18',
    requestedTimeSlot: '15h00 - 17h00',
    notes: 'Déjà réglé en totalité. Remettre à l’accueil.',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-001',
    tenantId: 'tenant-elegance',
    tenantName: 'Pressing Élégance Abidjan',
    userId: 'emp-bakary',
    userName: 'Bakary Soro',
    userRole: 'Gérant',
    action: 'CREATE_ORDER',
    category: 'order',
    timestamp: '2026-08-15 09:30:12',
    ipAddress: '160.155.201.45 (Abidjan)',
    device: 'Tablette Caisse Galaxy Tab A8',
    details: 'Création commande MPP-2026-0842 pour le client Amadou Koné - Montant: 7 500 FCFA',
  },
  {
    id: 'log-002',
    tenantId: 'tenant-elegance',
    tenantName: 'Pressing Élégance Abidjan',
    userId: 'emp-sarah',
    userName: 'Sarah Konan',
    userRole: 'Réceptionniste',
    action: 'PAYMENT_RECEIVED',
    category: 'financial',
    timestamp: '2026-08-15 09:32:05',
    ipAddress: '160.155.201.45',
    device: 'Tablette Caisse',
    details: 'Enregistrement règlement Wave 7 500 FCFA - Réf: WAVE-CI-20260815-99812',
  },
  {
    id: 'log-003',
    tenantId: 'tenant-elegance',
    tenantName: 'Pressing Élégance Abidjan',
    userId: 'owner-jeanmarc',
    userName: 'Jean-Marc Kouadio',
    userRole: 'Propriétaire',
    action: 'UPDATE_PERMISSIONS',
    category: 'security',
    timestamp: '2026-08-15 18:00:00',
    ipAddress: '41.207.128.10',
    device: 'MacBook Pro macOS',
    details: 'Modification des permissions pour le poste Réceptionniste (Droit d’accorder des remises désactivé)',
  },
  {
    id: 'log-004',
    userId: 'superadmin',
    userName: 'Super Admin Mon Pressing Pro',
    userRole: 'Super Admin / Éditeur',
    action: 'RECORD_SAAS_PAYMENT',
    category: 'saas_admin',
    timestamp: '2026-08-10 11:15:00',
    ipAddress: '154.68.10.22',
    device: 'Serveur Web Cloud Admin',
    details: 'Validation abonnement SaaS Pro pour Pressing Élégance Abidjan (50 000 FCFA via Wave)',
  },
];

export const INITIAL_SAAS_INVOICES: SaaSInvoice[] = [
  {
    id: 'inv-saas-001',
    invoiceNumber: 'FAC-SAAS-2026-0042',
    tenantId: 'tenant-elegance',
    tenantName: 'Pressing Élégance Abidjan',
    ownerName: 'Jean-Marc Kouadio',
    ownerPhone: '+225 07 08 12 34 56',
    ownerEmail: 'jm.kouadio@pressingelegance.ci',
    ownerAddress: 'Cocody Angré 8e Tranche, Abidjan',
    planTier: 'pro',
    planName: 'Formule PRO EXPANSION',
    billingCycle: 'monthly',
    coverageStartDate: '2026-08-10',
    coverageEndDate: '2026-09-10',
    subtotal: 50000,
    taxAmount: 0,
    totalAmount: 50000,
    paymentMethod: 'wave',
    transactionReference: 'WAVE-SAAS-20260810-0012',
    status: 'paid',
    issueDate: '2026-08-10',
    dueDate: '2026-08-15',
    paidDate: '2026-08-10',
    items: [
      {
        description: 'Abonnement Logiciel MON PRESSING PRO - Formule PRO (3 agences, 10 utilisateurs, livraisons & compta)',
        quantity: 1,
        unitPrice: 50000,
        total: 50000,
      },
    ],
    notes: 'Règlement instantané reçu via Wave Côte d’Ivoire. Licence active.',
  },
  {
    id: 'inv-saas-002',
    invoiceNumber: 'FAC-SAAS-2025-0018',
    tenantId: 'tenant-royal-prestige',
    tenantName: 'Royal Prestige Pressing CI',
    ownerName: 'Stéphane Bamba',
    ownerPhone: '+225 01 02 03 04 05',
    ownerEmail: 'sbamba@royalprestige.ci',
    ownerAddress: 'Boulevard de Marseille, Zone 4, Abidjan',
    planTier: 'premium',
    planName: 'Formule ENTERPRISE PREMIUM',
    billingCycle: 'yearly',
    coverageStartDate: '2025-11-15',
    coverageEndDate: '2026-11-15',
    subtotal: 950000,
    taxAmount: 0,
    totalAmount: 950000,
    paymentMethod: 'bank_transfer',
    transactionReference: 'VIR-SGBCI-20251115-992',
    status: 'paid',
    issueDate: '2025-11-15',
    dueDate: '2025-11-20',
    paidDate: '2025-11-15',
    items: [
      {
        description: 'Licence Annuelle Multi-Ateliers ENTERPRISE PREMIUM (Agences illimitées, Webhooks API, Support 24/7)',
        quantity: 1,
        unitPrice: 950000,
        total: 950000,
      },
    ],
    notes: 'Virement bancaire validé auprès de la SGBCI Abidjan.',
  },
  {
    id: 'inv-saas-003',
    invoiceNumber: 'FAC-SAAS-2026-0089',
    tenantId: 'tenant-ivoire-express',
    tenantName: 'Ivoire Express Blanchisserie',
    ownerName: 'Clarisse Yao',
    ownerPhone: '+225 07 77 88 99 11',
    ownerEmail: 'clarisse.yao@ivoirepress.ci',
    ownerAddress: 'Adjamé 220 Logements, Abidjan',
    planTier: 'basic',
    planName: 'Formule STARTER',
    billingCycle: 'monthly',
    coverageStartDate: '2026-07-10',
    coverageEndDate: '2026-08-10',
    subtotal: 25000,
    taxAmount: 0,
    totalAmount: 25000,
    paymentMethod: 'orange_money',
    transactionReference: 'IMPAYE-OM-EN-ATTENTE',
    status: 'overdue',
    issueDate: '2026-07-10',
    dueDate: '2026-07-15',
    items: [
      {
        description: 'Renouvellement Mensuel Formule STARTER (1 Agence)',
        quantity: 1,
        unitPrice: 25000,
        total: 25000,
      },
    ],
    notes: 'Échéance dépassée. Compte temporairement suspendu en attente de régularisation.',
  },
];

export const INITIAL_BROADCAST_NOTIFICATIONS: BroadcastNotification[] = [
  {
    id: 'notif-001',
    title: 'Mise à jour v3.4 : Nouveau Module Livraisons & Suivi Mobile',
    message: 'Chers partenaires gérants de pressing, la mise à jour intégrant la gestion des tournées livreurs et géolocalisation est désormais active sur vos comptes Pro et Enterprise !',
    type: 'info',
    target: 'all_tenants',
    createdAt: '2026-08-14 10:00',
    isRead: false,
  },
  {
    id: 'notif-002',
    title: 'Maintenance Serveurs Planifiée',
    message: 'Une optimisation des bases de données aura lieu ce dimanche de 02h00 à 03h00 GMT. Aucun impact sur vos caisses hors-ligne.',
    type: 'warning',
    target: 'all_tenants',
    createdAt: '2026-08-15 16:30',
    isRead: false,
  },
];

export const DEFAULT_EDITOR_OWNER_PERMISSIONS: SaaSEditorPermissions = {
  canViewOverview: true,
  canViewTenants: true,
  canCreateTenants: true,
  canEditTenants: true,
  canDeleteTenants: true, // Super Admin Owner only
  canAddAdditionalPressing: true,
  canImpersonateTenant: true,
  canSuspendTenant: true,
  canReactivateTenant: true,
  canExtendTrial: true,
  canRecordSaaSPayments: true,
  canManageInvoices: true,
  canManageSaaSPlans: true,
  canSendBroadcast: true,
  canViewAuditLogs: true,
  canManageCollaborators: true,
  canManageGlobalSettings: true,
  canResetDatabase: true, // Super Admin Owner only
};

export const DEFAULT_COLLABORATOR_PERMISSIONS: SaaSEditorPermissions = {
  canViewOverview: true,
  canViewTenants: true,
  canCreateTenants: true,
  canEditTenants: true,
  canDeleteTenants: false, // Strict protection: No collaborator can delete clients
  canAddAdditionalPressing: true,
  canImpersonateTenant: true,
  canSuspendTenant: true,
  canReactivateTenant: true,
  canExtendTrial: true,
  canRecordSaaSPayments: true,
  canManageInvoices: true,
  canManageSaaSPlans: false,
  canSendBroadcast: false,
  canViewAuditLogs: true,
  canManageCollaborators: false,
  canManageGlobalSettings: false,
  canResetDatabase: false, // Strict protection: No collaborator can reset database
};

export const INITIAL_SAAS_EDITOR_USERS: SaaSEditorUser[] = [
  {
    id: 'editor-gilles',
    name: 'Gilles Brice Atsé',
    email: 'atsegillesbrice@gmail.com',
    phone: '+225 01 04 81 80 92 / +225 07 97 70 96 93',
    role: 'super_admin',
    isOwner: true,
    status: 'active',
    lastLogin: '2026-08-21 08:30',
    mustChangePassword: false,
    hasCompletedFirstLogin: true,
    permissions: DEFAULT_EDITOR_OWNER_PERMISSIONS,
  },
  {
    id: 'editor-kouame',
    name: 'Kouamé N’Guessan (Support & Gérance)',
    email: 'k.nguessan@agibrico.ci',
    phone: '+225 05 06 07 08 09',
    role: 'collaborator',
    isOwner: false,
    status: 'active',
    lastLogin: undefined,
    defaultPassword: '1234',
    mustChangePassword: true,
    hasCompletedFirstLogin: false,
    permissions: DEFAULT_COLLABORATOR_PERMISSIONS,
  },
  {
    id: 'editor-fatou',
    name: 'Fatoumata Koné (Chargée Facturation)',
    email: 'f.kone@agibrico.ci',
    phone: '+225 07 44 55 66 77',
    role: 'billing_manager',
    isOwner: false,
    status: 'active',
    lastLogin: undefined,
    defaultPassword: '1234',
    mustChangePassword: true,
    hasCompletedFirstLogin: false,
    permissions: {
      ...DEFAULT_COLLABORATOR_PERMISSIONS,
      canCreateTenants: false,
      canEditTenants: false,
      canSuspendTenant: false,
      canRecordSaaSPayments: true,
      canManageInvoices: true,
    },
  },
];

export const INITIAL_SAAS_GLOBAL_SETTINGS: SaaSGlobalSettings = {
  publisherName: 'AGB Solutions Web & Mobiles',
  publisherAuthor: 'Gilles Brice Atsé',
  publisherPhone: '+225 07 08 09 10 11',
  publisherWhatsapp: '+225 07 08 09 10 11',
  publisherEmail: 'contact@agibrico.ci',
  publisherAddress: 'Abidjan, Cocody Riviera Bonoumin, Côte d’Ivoire',
  wavePaymentNumber: '+225 07 08 09 10 11',
  orangeMoneyMerchantCode: 'OM-CI-88992',
  mtnMoMoCode: 'MOMO-CI-44120',
  defaultTrialDays: 14,
  maintenanceMode: false,
  maintenanceNotice: '',
  taxRatePercent: 0,
  appVersion: '3.4.2 Pro B2B',
};

